version: "2"
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 1500
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 200
  method-lines:
    config:
      threshold: 600
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 80
  identical-code:
    config:
      threshold: 80
exclude_paths:
- test/*
- examples/*